import {Plus_Jakarta_Sans} from 'next/font/google'
import '../globals.css'
import Footer from '@/layout/footer/Footer'

const plus = Plus_Jakarta_Sans({
  subsets: ['vietnamese'],
  variable: '--font-plus-jakarta-sans',
})

export const metadata = {
  title: 'Du học Đức Anh',
  description: 'Generated by dev okhub',
}

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <body
        className={`${plus.className} ${plus.variable}`}
      >
        {children}
        <Footer />
      </body>
    </html>
  )
}
